### ISSUE TITLE
/auth/:provider route not registered?

### ISSUE THREAD

**Issue by retorquere** [auth0/omniauth-auth0#47] opened 2017-02-07 15:27 UTC
I'm hitting an issue where omniauth works in dev mode but not in production using passenger. Under passenger, I am redirected correctly by my app to `/auth/auth0` (as I use the auth0 provider) but then get an error from nginx that that url doesn't exist. This is my omniauth config:

```
configure do
  set :sessions, true
  set :session_secret, (ENV['SESSION_SECRET'].to_s == '' ? SecureRandom.base64 : ENV['SESSION_SECRET'])

  OmniAuth.configure do |config|
    # Always use /auth/failure in any environment
    config.failure_raise_out_environments = []
  end

  use OmniAuth::Builder do
    provider :auth0, ENV['AUTH0_CLIENT_ID'], ENV['AUTH0_CLIENT_SECRET'], ENV['AUTH0_DOMAIN']
  end
end
```

I've ran this to show my routes:

```
require_relative 'main' # my sinatra app

Sinatra::Application.routes["GET"].each do |route|
  puts route[0]
end
```

but that shows only these auth-related routes, even in my development environment:

```
(?-mix:\A\/auth\/([^\/?#]+)\/callback\z)
(?-mix:\A\/auth\/failure\z)
(?-mix:\A\/auth\/logout\z)
```

but these are all mine, I was expecting `/auth/auth0` (or a regex matching it) to be listed too.

**Comment by ClaudioFloreani** [comment] 2017-03-27 09:59
It's working for me.
I have these in my config/routes.rb:

````ruby
  # Auth0
  namespace 'auth' do
    scope ':provider' do
      get 'callback'
      get 'failure'
    end
  end
````

and when I `GET "/auth/auth0/failure"` it is rendered as expected

```
Processing by AuthController#failure as HTML
  Parameters: {"provider"=>"auth0"}
  Rendered auth/failure.html.erb within layouts/application (2.5ms)
Completed 200 OK in 1967ms (Views: 1965.9ms | ActiveRecord: 0.0ms)
 => 200 
```

What's in your route config?

**Comment by retorquere** [comment] 2017-03-27 11:42
I've converted the app to node in the interim, so I can't replicate the issue anymore, sorry.

**Comment by ClaudioFloreani** [comment] 2017-03-27 15:50
I think we can close this issue because nothing in this gem is interfering with Omniauth properly handling `'auth/:provider'`

**Comment by joshcanhelp** [comment] 2018-06-22 18:44
Tested and confirmed, this route is working fine (though it's configured in a few places, which is what might have caused this issue).

Looks like the first route matches?

![screenshot 2018-06-22 11 43 04](https://user-images.githubusercontent.com/855223/41793620-8664a22e-7611-11e8-9547-eb608d63d7c4.png)

**Closed by joshcanhelp** 2018-06-22 18:44 UTC
